name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'src/backend/**' ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Restore Dependencies
        run: dotnet restore src/backend/CryptoCloud.slnx

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"Roderic19_CryptoCloud" /o:"roderic19" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build src/backend/CryptoCloud.slnx --no-restore
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Run Tests
        run: dotnet test src/backend/CryptoCloud.slnx --no-restore --verbosity normal

      - name: Build and Publish
        run: |
          cd src/backend
          dotnet publish CryptoCloud.Backend.csproj -c Release -o ./publish

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Functions (Flex)'
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-cryptocloud-backend'
          package: './src/backend/publish'
